server:
  port: 8081

spring:
  application:
    name: harvest
  cloud:
    gcp:
      firestore:
        project-id: ${GCP_PROJECT_ID}
        emulator:
          enabled: true
        host-port: localhost:8082